### ISSUE TITLE
temp bans

### ISSUE THREAD

**Issue by Sonicscream** [Crptclvr/todo#49]
Temp bans do not appear to stick.

**Comment by Sonicscream** [comment]
`2020-07-02T21:59:16+0200 [stderr#error] Traceback (most recent call last):
2020-07-02T21:59:16+0200 [stderr#error]   File "/usr/local/lib/python3.7/site-packages/pyspades/protocol.py", line 167, in update
2020-07-02T21:59:16+0200 [stderr#error]     self.on_connect(peer)
2020-07-02T21:59:16+0200 [stderr#error]   File "/usr/local/lib/python3.7/site-packages/pyspades/protocol.py", line 111, in on_connect
2020-07-02T21:59:16+0200 [stderr#error]     connection.on_connect()
2020-07-02T21:59:16+0200 [stderr#error]   File "/usr/local/lib/python3.7/site-packages/piqueserver/scripts/afk.py", line 116, in on_connect
2020-07-02T21:59:16+0200 [stderr#error]     return connection.on_connect(self)
2020-07-02T21:59:16+0200 [stderr#error]   File "/home/server/aceofspades/hallway/scripts/cc_staff.py", line 154, in on_connect
2020-07-02T21:59:16+0200 [stderr#error]     return connection.on_connect(self)
2020-07-02T21:59:16+0200 [stderr#error]   File "/home/server/aceofspades/hallway/scripts/cc_homeAlone.py", line 68, in on_connect
2020-07-02T21:59:16+0200 [stderr#error]     return connection.on_connect(self)
2020-07-02T21:59:16+0200 [stderr#error]   File "/usr/local/lib/python3.7/site-packages/piqueserver/player.py", line 55, in on_connect
2020-07-02T21:59:16+0200 [stderr#error]     name, reason, timestamp = self.protocol.bans[client_ip]
2020-07-02T21:59:16+0200 [stderr#error] ValueError: too many values to unpack (expected 3)
`

**Comment by Sonicscream** [comment]
> 2020-07-02T21:59:16+0200 [stderr#error] Traceback (most recent call last):
2020-07-02T21:59:16+0200 [stderr#error]   File "/usr/local/lib/python3.7/site-packages/pyspades/protocol.py", line 167, in update
2020-07-02T21:59:16+0200 [stderr#error]     self.on_connect(peer)
2020-07-02T21:59:16+0200 [stderr#error]   File "/usr/local/lib/python3.7/site-packages/pyspades/protocol.py", line 111, in on_connect
2020-07-02T21:59:16+0200 [stderr#error]     connection.on_connect()
2020-07-02T21:59:16+0200 [stderr#error]   File "/usr/local/lib/python3.7/site-packages/piqueserver/scripts/afk.py", line 116, in on_connect
2020-07-02T21:59:16+0200 [stderr#error]     return connection.on_connect(self)
2020-07-02T21:59:16+0200 [stderr#error]   File "/home/server/aceofspades/hallway/scripts/cc_staff.py", line 154, in on_connect
2020-07-02T21:59:16+0200 [stderr#error]     return connection.on_connect(self)
2020-07-02T21:59:16+0200 [stderr#error]   File "/home/server/aceofspades/hallway/scripts/cc_homeAlone.py", line 68, in on_connect
2020-07-02T21:59:16+0200 [stderr#error]     return connection.on_connect(self)
2020-07-02T21:59:16+0200 [stderr#error]   File "/usr/local/lib/python3.7/site-packages/piqueserver/player.py", line 55, in on_connect
2020-07-02T21:59:16+0200 [stderr#error]     name, reason, timestamp = self.protocol.bans[client_ip]
2020-07-02T21:59:16+0200 [stderr#error] ValueError: too many values to unpack (expected 3)

**Comment by Sonicscream** [comment]
Last I checked this it appeared algorithm parsing bans was trying to split the ban reason string inside of the ban instead of the actual ban itself (which consists of 3 things: ip, time, reason). Need to investigate if this is my problem or a piqueserver problem.

**Comment by Sonicscream** [comment]
This might be fixed. I don't know :D lets find out.
